server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: anhproqn999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: "2QbAyVf+5QAwTjONMGpHAI9pg+43vqXUT43MWqF50Z3lhOvGTzvphfikaeI33/sd"
  valid-duration: 360000
  refreshable-duration: 864000

app:
  services:
    profile: http://localhost:8081/profile

google:
  clientId: "309829967812-k45di4ubndsbv94fft0cjhabgcikca1o.apps.googleusercontent.com"
  clientSecret: "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"
  redirectUri: "http://localhost:3000/authenticate"