server:
  port: 8888

app:
  api-prefix: /api/v1
  host-name: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://${app.host-name}:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://${app.host-name}:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://${app.host-name}:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: movie_service
          uri: http://${app.host-name}:8083
          predicates:
            - Path=${app.api-prefix}/movie/**
          filters:
            - StripPrefix=2
        - id: search_service
          uri: http://${app.host-name}:8084
          predicates:
            - Path=${app.api-prefix}/search/**
          filters:
            - StripPrefix=2
        - id: bills_service
          uri: http://${app.host-name}:8085
          predicates:
            - Path=${app.api-prefix}/bills/**
          filters:
            - StripPrefix=2