services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=identity_service
      - MYSQL_ROOT_PASSWORD=anhproqn999
    ports:
      - "3307:3306"
    volumes:
      - ./data_mysql:/var/lib/mysql

volumes:
  data_mysql:
    driver: local 