server:
  port: 8085
  servlet:
    context-path: /bills
spring:
  application:
    name: bill-service
  data:
    mongodb:
      uri: mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/?retryWrites=true&w=majority&appName=BackendDB
      database: movie-web

app:
  services:
    identity: http://localhost:8080/identity
  id: "2554"
  key1: "sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn"
  key2: "trMrHtvjo6myautxDUiAcYsVtaeQ8nhf"
  endpoint: "https://sb-openapi.zalopay.vn/v2"
  redirectedUrl: http://localhost:8085
  callbackUrl: http://localhost:8085