server:
  port: 8084
  servlet:
    context-path: /search

app:
  host-name: localhost

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/movie-web
