server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 123456789
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.website/realms/movie-web

app:
  services:
    identity: http://localhost:8080/identity